### PR TITLE
link to Adam's "Trigger a sequence" video from "Triggers" page

### PR DESCRIPTION
**Pull request by StackScribe**
Signed-off-by: Meg McRoberts <meg.mcroberts@dynatrace.com>

### CODE REVIEW

**Review by agardnerIT — COMMENTED** [review]
Tiny typo: `ilustrates`

**Comment by StackScribe** [comment]
> Tiny typo: `ilustrates`

Fixed

**Comment by agardnerIT** [comment]
When `triggeredOn` is used, the shipyard author is implicitly linking two sequences, tehrefore it probably wouldn't make sense to manually trigger the production sequence if it also has a `triggeredOn` block. Think of it like a Jenkins pipeline. If your production release pipeline triggers only when hardening is successful, that's fine. I can't imagine why you'd skip the UAT safeguards and instead manually trigger a production release.

**Comment by agardnerIT** [comment]
One final change and it's good to go: `If the delivery sequence fails because of a failed test task`. Reword that to `IF the delivery sequence fails`.

If any task is a sequence fails, the sequence fails and thus it would match your `fail` selector.

**Review by agardnerIT — CHANGES_REQUESTED** [review]
When `triggeredOn` is used, the shipyard author is implicitly linking two sequences, therefore it probably wouldn't make sense to manually trigger the production sequence if it also has a `triggeredOn` block. Think of it like a Jenkins pipeline. If your production release pipeline triggers only when hardening is successful, that's fine. I can't imagine why you'd skip the UAT safeguards and instead manually trigger a production release.

All that's to say, perhaps remove the section about HTTP `POST`ing to trigger the production sequence as it has a `triggeredOn` condition.

One final change and it's good to go: If the delivery sequence fails because of a failed test task. Reword that to `If the delivery sequence fails.`

If any task is a sequence fails, the sequence fails and thus it would match your fail selector.

**Comment by StackScribe** [comment]
I fixed the "If the delivery sequence fails..." sentence.  Are you okay with leaving the HTTP POST section alone for now?   I'm thinking that we have lots of problems with lots of the examples in what is now the "Define" section -- we can revisit everything as we try to put this together.

**Review by agardnerIT — APPROVED** [review]
LGTM

**Pull request merged**
