### PR TITLE
Add Keptn slack to xrefs that are ignored

### PR DESCRIPTION
**Pull request by StackScribe**
Signed-off-by: Meg McRoberts <meg.mcroberts@dynatrace.com>

### CODE REVIEW

**Review by aepfli — APPROVED** [review]

**Review by christian-kreuzberger-dtx — APPROVED** [review]
LGTM

**Comment by christian-kreuzberger-dtx** [comment]
FYI, I would like to see a better description in the Pull Request, or link a GH issue to it that describes the problem. I will provide an example of what I would have done below.
---

Recently during xref checks in our CI, we are getting the following error:
image
Example CI run: https://github.com/keptn/keptn.github.io/runs/7403101563?check_suite_focus=true

To fix this error, we are adding https://slack.keptn.sh into the list of things that are not to be checked.

**Comment by StackScribe** [comment]
Whoops, this is not the right solution.  See https://keptn.slack.com/archives/C01E3A84PJL/p1658317863109659 .  Of course, merging this would unblock the PRs that are failing the xref CI but perhaps it is good if we have an automated test that alerts us when slack.keptn.sh is no longer working?

**Comment by StackScribe** [comment]
I am merging this so we can merge other PRs while waiting for a good fix here.

**Pull request merged**
