### PR TITLE
Keptn status: sandbox to incubating.

### LINKED ISSUE #1320: Refactor the Keptn project status
**Describe the bug**

I see on the Keptn website, that "We are a CNCF Sandbox Project", while Keptn is one of the CNCF Incubating projects now!
Snapshot from [keptn.sh](https://keptn.sh/):

Screenshot from 2022-07-26 10-10-59

FYI: You can find the above image at [keptn/keptn.github.io](https://github.com/keptn/keptn.github.io/blob/master/static/images/home/cloud-native-computing-foundation.svg).

**To Reproduce**

Replace this sentence with, "We are a CNCF Incubating project".
Snapshot from [CNCF landscape](https://landscape.cncf.io/?selected=keptn):

Screenshot from 2022-07-26 10-40-45

### PR DESCRIPTION
**Pull request by prateek041**
Fixes #1320 

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix

### CODE REVIEW

**Comment by mehabhalodiya** [comment]
@prateek041 I am happy to review this but first, you need to fix the DCO Action. You can head over to the `Details` to find the instructions, that need to be done (mandatory) in order to pass the check. Thank you!

**Review by mehabhalodiya — COMMENTED** [review]
Replace "incubating" with "Incubating".
The initial letter should be capitalized.

Tip: Please read the issue description carefully. I have mentioned the way we need it in the `To Reproduce` section.

**Comment by mehabhalodiya** [comment]
@prateek041 One more thing, I noticed you work on `master` branch. Please avoid making the changes on the `main` or `master` branch in any project. Always consider switching on the new one 🙂

**Comment by mehabhalodiya** [comment]
I noticed you have removed a full stop. It should be:
`We are a CNCF Incubating project.`

**Comment by prateek041** [comment]
About the full stop, we don't usually use them in design elements like that, so I unconsciously skipped it. Let me correct it asap.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Inefficient

**Comment by mehabhalodiya** [comment]
@prateek041 can you please squash the commits?

**Comment by prateek041** [comment]
Squashed the commits and made the changes. Please check if any more changes are required.

__
[sema-logo](https://semasoftware.com/gh) &nbsp;**Summary:** :hammer_and_wrench: This code needs a fix&nbsp; | &nbsp;**Tags:** Not reusable

**Review by mehabhalodiya — APPROVED** [review]
LGTM!
Thanks for contributing to Keptn 🎉

**Review by oleg-nenashev — APPROVED** [review]
Thanks!

**Pull request merged**
