### PR TITLE
remove the colliding of buttton in the integration docs 

### PR DESCRIPTION
**Pull request by Nitishupkr**
Signed-off-by: Nitishupkr [nitishupkr@gmail.com](mailto:nitishupkr@gmail.com)
fixes : #1640 
the text buttons which are colliding are now fixed they are not colliding and its is responsive to the all device .And a Netlify build is ready to be used so we can display the page and check the docs section of the integration
see:https://friendly-longma-79936e.netlify.app/docs/integrations/

### CODE REVIEW

**Comment by Nitishupkr** [comment]
Signed-off-by: Nitish Tiwari  nitishupkr@gmail.com

**Review by StackScribe — COMMENTED** [review]
lgtm but I'm going to let someone with more knowledge approve it.  Thanks for doing this, @Nitishupkr !

**Comment by Nitishupkr** [comment]
@StackScribe  please see it ones

**Comment by Nitishupkr** [comment]
@johannes-b please see it

**Review by agardnerIT — APPROVED** [review]

**Pull request merged**
