### PR TITLE
Adding copyright to footer as per CNCF website guidelines

### PR DESCRIPTION
**Pull request by nate-double-u**
Adding copyright to footer:
- Keptn authors
- Linux foundation

fixes: https://github.com/keptn/keptn.github.io/issues/717

### CODE REVIEW

**Comment by nate-double-u** [comment]
Deploy preview: https://deploy-preview-718--keptn.netlify.app/

**Comment by nate-double-u** [comment]
Last push corrects the footer as it wasn't initially picking up the project name param from the config file.

**Comment by jetzlstorfer** [comment]
Thanks @nate-double-u for adding this section.
The project is released under Apache License 2.0 - does this conflict with the License you referred to in the PR?

**Comment by christian-kreuzberger-dtx** [comment]
So right now Keptn docs (or at least this repository :) ) is licenced under Apache 2.0.
IMO docs and images should use Creative commons (CC) - see https://creativecommons.org/licenses/by/4.0/ for details.
Though I'm not sure whether using Apache 2.0 is a problem, maybe @nate-double-u can has an idea?

**Comment by christian-kreuzberger-dtx** [comment]
Just had a quick look:
Helm docs have the same statement about CC 4.0, but they use MIT in their repository. Harbor also has the CC 4.0 statement on the website, and uses Apache 2.0 in their repo.

**Comment by nate-double-u** [comment]
Here's a conversation about CC-BY 4 vs Apache 2 we had over on the Dex IdP site:
https://github.com/dexidp/website/pull/9#issuecomment-702372163

> ...code is Apache v2.0 and docs are CC-BY 4.0 in CNCF as indicated in the charter
\- @caniszczyk

So I don't think that having the site/repo licensed under Apache 2 and the docs using CC-BY 4 is a problem. There's a few sites in the CNCF using this same setup ([dexidp.io](https://dexidp.io) & [cni.dev](https://www.cni.dev) included)

**Comment by nate-double-u** [comment]
Chris suggests in the conversation linked that we could also add a "LICENSE-DOCS" to the repo if that makes things clearer, but that's a personal preference.

**Comment by christian-kreuzberger-dtx** [comment]
> So I don't think that having the site/repo licensed under Apache 2 and the docs using CC-BY 4 is a problem. There's a few sites in the CNCF using this same or similar setup.

I'm fine with doing it like all the others do. Okay for you too @jetzlstorfer ?

**Comment by jetzlstorfer** [comment]
My only concern is that if we mix Apache 2 and CC-BY 4 it is not reflected in our LICENSE files.
Keptn main repo: https://github.com/keptn/keptn/blob/master/LICENSE 
Keptn website & docs https://github.com/keptn/keptn.github.io/blob/master/LICENSE 

Therefore I would go with Apache 2 all the way to avoid confusion. Or am I missing the point?

**Comment by jetzlstorfer** [comment]
Sorry, should have read the comment and discussion from Chris before. 
Yes, it is fine to have two different licenses.
Is it best practice to add a dedicated LICENSE-DOCS in the website/docs repo?

**Comment by nate-double-u** [comment]
>  Is it best practice to add a dedicated LICENSE-DOCS in the website/docs repo?

I'm not entirely sure to be honest. The way this PR is set up is the way a couple other sites in the CNCF have been setup.

That said, I did some looking around for examples. A good one I found is Docusaurus. They have two licenses in their repo too, and mentions them in their README:
* https://github.com/facebook/docusaurus#license
* https://github.com/facebook/docusaurus/blob/master/LICENSE
* https://github.com/facebook/docusaurus/blob/master/LICENSE-docs

I like this practice as it does provide a very clear explanation of the LICENSEs and what they cover.

**Comment by nate-double-u** [comment]
I've pushed a commit that adds a LICENSE-docs file, and updates the README for clarity. 
(I didn't squash and force push in case we don't want to go this route, and if we do, we can use GitHub's squash on merge tool).

**Note**: this is a verbatim copy of the LICENSE-docs file from Docusaurus (https://github.com/facebook/docusaurus/blob/master/LICENSE-docs). I wasn't able to find the text on the Creative Commons site. The closest I found was this page: https://creativecommons.org/licenses/by/4.0/legalcode.

**Comment by nate-double-u** [comment]
last force push fixes a typo in the README file.

**Review by jetzlstorfer — APPROVED** [review]
lgtm

**Comment by jetzlstorfer** [comment]
thanks @nate-double-u ! 
I am fine with the changes. 
@christian-kreuzberger-dtx any objections?

**Review by christian-kreuzberger-dtx — APPROVED** [review]
Looks good to me

**Comment by nate-double-u** [comment]
Thanks everyone!

**Pull request merged**
