### PR TITLE
remove resources/_gen #761

### LINKED ISSUE #761: Make sure auto-generated files are not commited to git
As discussed in https://github.com/keptn/keptn.github.io/pull/758, we often have files in resources/_gen/ folder in our PRs.

That's certainly not what we want, as they are autogenerated.

# Definition of Done
- [ ] Auto-generated css/js/html/... files are no longer part of PRs
- [ ] Website and netlify deploy still works as expected

### PR DESCRIPTION
**Pull request by DarthBenro008**
- Fixes #761 
- Removed the whole resources/_gen as its auto-generated when the hugo command is run.
- This PR has been deployed on https://keptndocs.benro.tech for testing purposes to ensure Netlify is able to deploy the website properly

image

### CODE REVIEW

**Comment by christian-kreuzberger-dtx** [comment]
Sorry for the late response. It seems that something is not working with our netlify deploy preview/step:
```
10:06:59 AM: Executing user command: hugo
10:07:00 AM: Building sites …
10:07:00 AM: ERROR 2021/04/15 08:07:00 error: failed to transform resource: TOCSS: failed to transform "scss/style.scss" (text/x-scss): this feature is not available in your current Hugo version
10:07:14 AM: Total in 14693 ms
10:07:14 AM: Error: Error building site: logged 1 error(s)
```

**Comment by jetzlstorfer** [comment]
I was running a test locally and it is working on my End with Hugo 0.55
```
hugo version
Hugo Static Site Generator v0.55.4/extended darwin/amd64 BuildDate: unknown
```

Which Hugo version did you try with Netlify @DarthBenro008 ?

**Comment by jetzlstorfer** [comment]
I've now changed the Ubuntu image to 16.04 to be able to upgrade to Hugo 0.55 on the netlify build.
This is the build: https://app.netlify.com/sites/keptn/deploys/609bc147bd8a741008801a6e 
However, the outcome is missing the navigation on the very top: https://609bc147bd8a741008801a6e--keptn.netlify.app/ 

@DarthBenro008 can you please share your settings so we can have a look

**Comment by DarthBenro008** [comment]
@jetzlstorfer @christian-kreuzberger-dtx I was looking into this issue, turns out I had not specified any environment variable on netlify, hence Netlify build it with the latest version for my builds.

However while developing I ran `hugo 0.51 extended` locally as instructed in the [readme](https://github.com/keptn/keptn.github.io#run-locally)
image


I set my version HUGO_VERSION to 0.53 manually on Netlify and re-triggered the build (also ensuring to purge any image caching).

image

running ubuntu 16.04 on Netlify by default:
image


These are the logs and it builds successfully: https://app.netlify.com/sites/hopeful-jones-ae4868/deploys/609bcc3eab0052fe0d11ee56

The build result can be checked here: https://keptndocs.benro.tech/ **or** https://609bcc3eab0052fe0d11ee56--hopeful-jones-ae4868.netlify.app/ 

I suggest overcoming such issues by adding `HUGO_VERSION` in the `netlify.toml` file as mentioned in the [Netlify docs](https://gohugo.io/hosting-and-deployment/hosting-on-netlify/#configure-hugo-version-in-netlify)

**Comment by jetzlstorfer** [comment]
Hi @DarthBenro008 
I verified with Ubuntu 16.04 and HUGO_VERSION 0.53 and this is now working it seems.

**Review by jetzlstorfer — CHANGES_REQUESTED** [review]
this file https://github.com/keptn/keptn.github.io/pull/769/files#diff-e2444f78c0410156756b2fc75210f03141913bca28615d88f4809f0633d12278 
should not be removed

**Comment by DarthBenro008** [comment]
Hey, @jetzlstorfer thanks for pointing that out! It's really weird that a folder/file that was included in .gitignore was tracked and pushed 😅 . Nevertheless, I have added it back. Should I create an issue to add the `HUGO_VERSION` in `netlify.toml` file as mentioned in the [Netlify docs](https://gohugo.io/hosting-and-deployment/hosting-on-netlify/#configure-hugo-version-in-netlify)? I think this would help contributors to have a similar environment when they host it on their netlify account for development/testing purposes

**Comment by jetzlstorfer** [comment]
Hi @DarthBenro008 yes please create an issue and if possible even a PR to fix it :) 
Thanks!

**Review by jetzlstorfer — APPROVED** [review]
LGTM

**Pull request merged**
