### PR TITLE
Add `helm repo add` step

### PR DESCRIPTION
**Pull request by cdhunt**
Fixes [#8727](https://github.com/keptn/keptn.github.io/issues/1408)

I was able to install after adding the repo to helm.

### CODE REVIEW

**Comment by agardnerIT** [comment]
I wasn't. Hmmm

```
$ helm repo add keptn https://charts.keptn.sh
"keptn" has been added to your repositories

$ helm install keptn keptn --repo=https://charts.keptn.sh -n keptn --create-namespace --set=apiGatewayNginx.type=LoadBalancer --set=continuousDelivery.enabled=true --wait
Error: Chart.yaml file is missing
```

**Comment by cdhunt** [comment]
Probably need to add `helm repo update` as well. I'll update and rebase.

**Comment by agardnerIT** [comment]
https://github.com/keptn/keptn/issues/8727

**Comment by StackScribe** [comment]
You have xref errors that have been fixed in master.  I tried just rerunning the checks and it still doesn't work.  I think if you modify the content (which it sounds like you will be), the errors will go away.  If not, `git fetch --all --prune; git merge upstream/master; push` should do it.

**Review by oleg-nenashev — COMMENTED** [review]
I guess it is ready to go after restoring "--set=continuousDelivery.enabled=true". We still use it in the Quick Start IIUC

**Comment by aepfli** [comment]
@cdhunt  thank you for this contribution, but sadly, I think this was somewhat superseded by https://github.com/keptn/keptn.github.io/issues/1509 and can therefore be closed - @StackScribe, or am I wrong here :)

**Comment by thisthat** [comment]
Closing because of superseded by #1509

**Pull request closed without merging**
