### PR TITLE
Update `quickstart` with k3d version `5.3.0`

### PR DESCRIPTION
**Pull request by Omkar0114**
https://github.com/keptn/keptn.github.io/issues/1065

### CODE REVIEW

**Comment by Omkar0114** [comment]
Hey, @StackScribe I made PR for changing the version of k3d. suggest the changes with review this :)

**Comment by Omkar0114** [comment]
#1065 fixes

**Comment by StackScribe** [comment]
A couple "best practices" notes:
* For a PR that is associated with a github issue, your description should include a link to that issue.  Just copy the URL of the issue and paste it into your discussion -- github will "prettify" it for you
* Also, using _index.md or index.md to identify the file changed is not terribly useful since every content file in the set has one of these names.  For this PR, I would reference "quickstart" as a meaningful identifier.

**Review by StackScribe — CHANGES_REQUESTED** [review]
I'm not sure that these changes should be made to this file.  Did you try running the Quickstart exercises with the new version of k3d?   I suspect that you did not -- at least not successfully -- because there are some issues with this guide right now.  But the text is to explicitly say what version of the software was used to test these exercises even if other places in the documentation recommend using a different version.  

Let's let this PR sit here.  You need to find the other occurrences of "k3d" in the doc set.  Many of them will not require modification but you need to read all of them, in context, and fix those that require it.  An easy way to find everything is to go to  the root directory of your clone of your fork and issue the "git grep -i k3d" command -- the -i option makes it case insensitive so it will find k3d, K3d, K3D, etc.  I think most of the hits you will get are in the "Installation" section but there may be some outside that section.  You can create a new PR that fixes anything that needs fixing.

**Comment by Omkar0114** [comment]
> A couple "best practices" notes:
> 
> * For a PR that is associated with a github issue, your description should include a link to that issue.  Just copy the URL of the issue and paste it into your discussion -- github will "prettify" it for you
> * Also, using _index.md or index.md to identify the file changed is not terribly useful since every content file in the set has one of these names.  For this PR, I would reference "quickstart" as a meaningful identifier.

Yep. Thanks a lot for suggesting it. I'll keep it in mind for sure!

**Review by oleg-nenashev — APPROVED** [review]
No objections as long as it was tested

**Comment by aepfli** [comment]
@Omkar0114 thank you for this contribution but sadly, I think this was somewhat superseded by #1509 and can therefore be closed - @StackScribe, or am I wrong here :)

**Pull request closed without merging**
