### PR TITLE
Updated footer.html

### LINKED ISSUE #1344: Tidy up footer links
The footer links have some duplicated content and the sections are generally outdated as we've added new content

image

Remove the duplicates

### PR DESCRIPTION
**Pull request by Omkar0114**
fixes #1344
1. I removed the `Docs` & `Tutorials` Parts from Resources.
2. Added `s` to `integration`
3. Added `Explore Keptn` which takes us to the link: https://keptn.sh/docs/explore/

Signed-off-by: Omkar kulkarni [88308267+Omkar0114@users.noreply.github.com](mailto:88308267+Omkar0114@users.noreply.github.com)

### CODE REVIEW

**Comment by Omkar0114** [comment]
Hey, @agardnerIT I made the changes, can you review them?

**Comment by agardnerIT** [comment]
Thanks for the quick turnaround! Perhaps the Integrations link should point to here as the "master record": https://keptn.sh/docs/integrations/

**Review by Omkar0114 — COMMENTED** [review]
not able to do with the very first commit!

**Comment by agardnerIT** [comment]
Apart from the DCO (which I don't know how to fix and I've hit this scenario numerous times myself), it all LGTM.

**Comment by Omkar0114** [comment]
Okay. will see about DCO. Thanks a lot, @agardnerIT for guiding 😃. When it will be merged?

**Comment by Omkar0114** [comment]
Hey, @oleg-nenashev @johannes-b Can you review this PR? :)

**Review by johannes-b — APPROVED** [review]
lgtm

**Review by StackScribe — APPROVED** [review]

**Comment by johannes-b** [comment]
Hi @Omkar0114 , 

the changes look good, but for some reason a test is failing. Can you please take a look here: https://github.com/keptn/keptn.github.io/runs/7742032705?check_suite_focus=true

**Comment by agardnerIT** [comment]
Failing due to broken links on a very old (`0.14.x`) release which are not touched by this PR.

**Comment by Omkar0114** [comment]
Sure. I checked this! Can anyone suggest to me what should I do exactly to pass the test? @agardnerIT @johannes-b

**Pull request merged**
