### PR TITLE
"tod deliver" -> "to deliver" (first PR)

### PR DESCRIPTION
**Pull request by StackScribe**
@oleg-nenashev

### CODE REVIEW

**Review by johannes-b — APPROVED** [review]
lgtm

**Review by oleg-nenashev — CHANGES_REQUESTED** [review]
The commits need to be signed off.
Personally I see no value in that for the documentation site, working on EasyCLA replacement

**Comment by StackScribe** [comment]
I did:
git commit --amend --no-edit --signoff
git pull
git push -f origin master
git push

A couple extra steps beyond what is in the doc but I now see that signoff commit here.

**Comment by StackScribe** [comment]
I tried doing another commit just to try to get the signoff but I don't think it worked.  Perhaps I should just close this PR and do a new one?

**Comment by StackScribe** [comment]
This PR is replaced by https://github.com/keptn/keptn.github.io/pull/1033 .

**Pull request closed without merging**
