### PR TITLE
Fix problem with teaser banner and header

### PR DESCRIPTION
**Pull request by martinhellwagner**

### CODE REVIEW

**Comment by jetzlstorfer** [comment]
Thanks for the PR - reviewing right now :)

**Comment by martinhellwagner** [comment]
@jetzlstorfer 

Basically, you just have to remove or comment out `{{ partial "announcement.html" . }}` in order for the header to be pushed up correctly. When you are ready to show the teaser banner again, add or comment in the partial again. 🙂

**Comment by jetzlstorfer** [comment]
works as advertised :) 

but there is an animation each time the page is reloaded. can we remove this animation? for the first 0.5 seconds or so the teaser and the menu are overlapping. if there is no teaser, it looks good, no animation there.

**Comment by jetzlstorfer** [comment]
@martinhellwagner I fixed it by making the "pushed-down version" the default one and doing the "move" of the navigation one the announcement is not present. This way it feels a bit smoother. Could you please have a look if I did it correctly?

**Comment by martinhellwagner** [comment]
@jetzlstorfer 

Looks good! You could also check for `if (!teaser && teaser == null)` for an extra layer of checks, but I guess in our case, the `null` check should be fine as well.

**Comment by jetzlstorfer** [comment]
thanks for the input @martinhellwagner ! I'll have it reviewed and we'll merge it

**Review by jetzlstorfer — APPROVED** [review]
lgtm

**Pull request merged**
