### PR TITLE
Facelift of website

### PR DESCRIPTION
**Pull request by AloisReitbauer**

### CODE REVIEW

**Comment by martinhellwagner** [comment]
@dirkwall @christian-kreuzberger-dtx 

Since I've cleaned up the repo and changed quite a bit of code, could you maybe have a close look at the docs and check that nothing is broken? I've had a first look myself, and it seems fine – but you definitely have a better insight into the Docs code than me.

**Comment by christian-kreuzberger-dtx** [comment]
I will take a look.

FYI, I believe the following link
Screenshot from 2019-12-09 16-14-20


should not point to the keptn.github.io repo but to https://github.com/keptn/keptn

**Comment by martinhellwagner** [comment]
@christian-kreuzberger-dtx 

Got it – I've changed the link. Thanks for pointing that out!

**Comment by christian-kreuzberger-dtx** [comment]
Regarding the changes done, I don't think that you broke anything from our main documentation, so that should be fine.

The only thing that I can see is that listings (both with numbers and with bullets) are a little bit of to the left, which is kind of distracting for docs/tutorials:

Screenshot from 2019-12-09 16-17-07

**Comment by martinhellwagner** [comment]
@christian-kreuzberger-dtx 

Fixed with the latest deploy. 👍

**Comment by christian-kreuzberger-dtx** [comment]
Looks much better now, thank you.

**Comment by martinhellwagner** [comment]
@dirkwall @christian-kreuzberger-dtx 

Just pushed a very small change arising from browser testing. Good to merge whenever you are ready. 🙂

**Comment by martinhellwagner** [comment]
@dirkwall @christian-kreuzberger-dtx

Just pushed a very small change arising from browser testing and added a custom 404 page. Good to merge whenever you are ready. 🙂

**Pull request merged**
