### PR TITLE
docs: Add 0.18.x documentation

### PR DESCRIPTION
**Pull request by thisthat**
Signed-off-by: Giovanni Liva <giovanni.liva@dynatrace.com>

The failing HTLM tests are due to links that are pointing toward the official website (https://keptn.sh) for a folder 0.18.x that doesn't exist since this PR is not merged yet :)

### CODE REVIEW

**Review by StackScribe — APPROVED** [review]
Interesting wrinkle about the xref checker.  I'll make sure the xrefs are good on my first PR.  Hopefully these problems will go away with the new doc engine.

**Comment by aepfli** [comment]
> Interesting wrinkle about the xref checker. I'll make sure the xrefs are good on my first PR. Hopefully these problems will go away with the new doc engine.

It is my bad, the adaption to the pipeline is only working with digits and not with digits and letters - https://github.com/keptn/keptn.github.io/blob/c0063956cc861dbf7b3f5b6c42460e6190c6185d/.github/workflows/auto-update.yml#L76

this regex would need to be improved to also cover the `*.*.x` naming

**Comment by aepfli** [comment]
nvm - this documentation update was not done via the auto-update mechanism, which runs the 

```
           find $DOCS_PATH -print -type f -name '*.md' -exec sed -i "s@https://keptn.sh/docs/[[:digit:]][^/]*/@${RELATIVE_PATH}@g" {} \; 
```

but manually, hence that, this is not incorporated. @thisthat can you run following command and push the changes?

```
          find ./content/docs/0.18.x/reference/cli/commands -print -type f -name '*.md' -exec sed -i "s@https://keptn.sh/docs/[[:digit:]][^/]*/@../../../../@g" {} \;
```

**Comment by thisthat** [comment]
Done @aepfli ! Thank you for the support! 🙌

**Comment by aepfli** [comment]
> Done @aepfli ! Thank you for the support! raised_hands

I am glad I could help. -> the new error is out of my hand :)

**Comment by thisthat** [comment]
> > Done @aepfli ! Thank you for the support! raised_hands
> 
> I am glad I could help. -> the new error is out of my hand :)

That's a flaky URL 😓 Opening them manually they work!

**Pull request merged**
